### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [allencoin/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured this step out :)

**Comment by allencoin** [comment]
Hi Marco, 

I think I found the issue. Definitely looks better on my iPad and phone now. 

https://github.com/allencoin/splurty/commit/3251169cdc33db4b99937be44d4ae9daf95a09b9

Let me know what you think!
